export {
  buildReportBaseName,
  fixedProjectFolders,
  folderActions,
  folderStatuses,
  materialDeleteActions,
  materialObjectTypes,
  moduleStatuses,
  reviewModules,
  type FixedProjectFolderCode,
  type FixedProjectFolderName,
  type FolderAction,
  type FolderStatus,
  type MaterialDeleteAction,
  type MaterialObjectType,
  type ModuleStatus,
  type ReviewModuleConfig,
} from "../../../../packages/review-core/src/projectStructure";
